// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/besapuz/gofer-man/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// AccrualServiceInterface is an autogenerated mock type for the AccrualServiceInterface type
type AccrualServiceInterface struct {
	mock.Mock
}

// GetAccrual provides a mock function with given fields: ctx, orderNumber
func (_m *AccrualServiceInterface) GetAccrual(ctx context.Context, orderNumber string) (*domain.AccrualResponse, error) {
	ret := _m.Called(ctx, orderNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetAccrual")
	}

	var r0 *domain.AccrualResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.AccrualResponse, error)); ok {
		return rf(ctx, orderNumber)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.AccrualResponse); ok {
		r0 = rf(ctx, orderNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AccrualResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAccrualServiceInterface creates a new instance of AccrualServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccrualServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccrualServiceInterface {
	mock := &AccrualServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
