// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/besapuz/gofer-man/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// BalanceRepositoryInterface is an autogenerated mock type for the BalanceRepositoryInterface type
type BalanceRepositoryInterface struct {
	mock.Mock
}

// AddAccrual provides a mock function with given fields: ctx, userID, accrual
func (_m *BalanceRepositoryInterface) AddAccrual(ctx context.Context, userID int, accrual float64) error {
	ret := _m.Called(ctx, userID, accrual)

	if len(ret) == 0 {
		panic("no return value specified for AddAccrual")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, float64) error); ok {
		r0 = rf(ctx, userID, accrual)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBalance provides a mock function with given fields: ctx, userID
func (_m *BalanceRepositoryInterface) GetBalance(ctx context.Context, userID int) (*domain.Balance, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 *domain.Balance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*domain.Balance, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *domain.Balance); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Balance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWithdrawals provides a mock function with given fields: ctx, userID
func (_m *BalanceRepositoryInterface) GetWithdrawals(ctx context.Context, userID int) ([]*domain.Withdrawal, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetWithdrawals")
	}

	var r0 []*domain.Withdrawal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]*domain.Withdrawal, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []*domain.Withdrawal); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Withdrawal)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Withdraw provides a mock function with given fields: ctx, userID, orderNumber, amount
func (_m *BalanceRepositoryInterface) Withdraw(ctx context.Context, userID int, orderNumber string, amount float64) error {
	ret := _m.Called(ctx, userID, orderNumber, amount)

	if len(ret) == 0 {
		panic("no return value specified for Withdraw")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string, float64) error); ok {
		r0 = rf(ctx, userID, orderNumber, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBalanceRepositoryInterface creates a new instance of BalanceRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBalanceRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *BalanceRepositoryInterface {
	mock := &BalanceRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
